---
abstract: 'Write JSON with simplicities'
author:
  - 'Lucas Tiago de Moraes <lucastiagodemoraes@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WJSON
provides:
  WJSON:
    file: lib/WJSON.pm
    version: '0.01'
requires:
  Encode: '0'
  JSON: '0'
  Moose: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.01'
